export const ErrorCode = {
  INVALID_REQUEST:    'INVALID_REQUEST',
  INVALID_IMAGE_URL:  'INVALID_IMAGE_URL',
  IMAGE_TOO_LARGE:    'IMAGE_TOO_LARGE',
  UNSUPPORTED_FORMAT: 'UNSUPPORTED_FORMAT',
  NO_TEXT_FOUND:      'NO_TEXT_FOUND',
  RATE_LIMIT:         'RATE_LIMIT',
  VISION_API_FAILURE: 'VISION_API_FAILURE',
  INVALID_PAYLOAD:    'INVALID_PAYLOAD',
  RENDER_FAILURE:     'RENDER_FAILURE',
  INTERNAL:           'INTERNAL',
} as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];